name: gi_english_website
description: Gi 글림아일랜드 어학원 / 스피킹되는 영어학원 글림아일랜드 파주운정 / 해외연계 프로그램 / 영어토론 / 초중등 실용영어

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  syncfusion_flutter_calendar: ^20.1.59
  table_calendar: ^3.0.9
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  url_launcher: ^6.1.7
  url_launcher_web: ^2.0.13
  intl: ^0.18.1
  image_picker: ^0.8.7+4
  photo_view: ^0.14.0
  file_picker: ^5.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/schoolMainImage.png
     - assets/schoolLogo.png
     - assets/loginButton.png
     - assets/instaLogo.png
     - assets/aboutMainImage.png
     - assets/cafeLogo.png
     - assets/mainGateImageMiddleSchool.png
     - assets/mainLogoPurple.png
     - assets/curriculumImage.png
     - assets/schoolAboutImage.png
     - assets/programMainImage.png
     - assets/communityMainImage.png
     - assets/giAppBanner.png
     - assets/giAppBannerArrow.png
     - assets/snsArrow.png
     - assets/giAppDownload.png
     - assets/mobileSchoolMainImage.png
     - assets/cafeMainImage.png
     - assets/cafeMainCatch.png
     - assets/schoolMainCatch.png
     - assets/ballPoolImage.png
     - assets/cafeLogoWithColor.png
     - assets/schoolLogoWithColor.png
     - assets/giEmblem.png
     - assets/kindyTimetable.png
     - assets/aucklandView.png
     - assets/miaKimPhoto.jpg
     - assets/eleTimetableTuesThurs.png
     - assets/eleTimetableMWF.png
     - assets/scholasticLogo.jpg
     - assets/wonderCodeLogo.jpg
     - assets/giAppBannerFinal.png
     - assets/giKidsWeekendLogo.png
     - assets/mobileLoginButton.png
     - assets/map.jpg
     - assets/whyChooseNzClip.png
     - assets/schoolList.png
     - assets/schoolSelection.png
     - assets/whyTaurangaClipWeb.png
     - assets/kinderTimesLogo.png
     - assets/juniorTimesLogo.png
     - assets/eleOnlineLink.png
     - assets/middleOnlineLink.png
     - assets/nieAd.png
     - assets/nieAd2.png
     - assets/trophyAd1.png
     - assets/trophyAd2.png
     - assets/bulletinBoardBG.png
     - assets/mainBannerOpening.png
     - assets/naverBlogLogo.png
     - assets/mainGateImageSimple.png
     - assets/mainGateImageBlack.png
     - assets/gleamIslandLogo.jpeg
     - assets/gleamIslandMoto.png
     - assets/middleTimetableTTS.png
     - assets/middleTimetableMWF.png
     - assets/gleamIslandMoto1.png
     - assets/gleamIslandMoto2.png
     - assets/optionalPrograms.png
     - assets/eleProgramPeriod.png
     - assets/elePrep.png
     - assets/eleProgram.png
     - assets/nie.png
     - assets/nzMiddleSchoolList.png
     - assets/whyTaurangaInfo.png
     - assets/whyNZInfo.png
     - assets/middleSchoolProgramInfo.png
     - assets/middleSchoolOptionalProgram.png
     - assets/middleTimetableTT.png
     - assets/mainEnterance.jpeg
     - assets/lobby1.jpeg
     - assets/doors.jpeg
     - assets/gleamIslandLogo.jpeg
     - assets/teachers.png
     - assets/car1.jpeg
     - assets/car2.jpeg
     - assets/car3.jpeg
     - assets/lobby.jpeg
     - assets/lobby2.jpeg
     - assets/classroom.jpeg
     - assets/lab.jpeg
     - assets/scienceday.jpeg
     - assets/projectart.jpeg
     - assets/giProgramPeriod.png
     - assets/directorPhoto.jpeg
     - assets/tuitionFeeChart.jpeg










  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf

    - family: MaruBuri
      fonts:
        - asset: assets/fonts/MaruBuri-ExtraLight.otf
        - asset: assets/fonts/MaruBuri-Light.otf
        - asset: assets/fonts/MaruBuri-Regular.otf
        - asset: assets/fonts/MaruBuri-SemiBold.otf
        - asset: assets/fonts/MaruBuri-Bold.otf

    - family: Jalnan
      fonts:
        - asset: assets/fonts/Jalnan-Regular.otf

    - family: LucidaCalligraphy
      fonts:
        - asset: assets/fonts/LucidaCalligraphy-Itelic.TTF

    - family: Behappy
      fonts:
        - asset: assets/fonts/Behappy.ttf

    - family: Decoshadow
      fonts:
        - asset: assets/fonts/Decoshadow.ttf

    - family: Lovingu
      fonts:
        - asset: assets/fonts/Lovingu.ttf

    - family: Oneprettynight
      fonts:
        - asset: assets/fonts/Oneprettynight.ttf

    - family: Cafe24Syongsyong
      fonts:
        - asset: assets/fonts/Cafe24Syongsyong.ttf

    - family: SCDream
      fonts:
        - asset: assets/fonts/SCDream1.otf
        - asset: assets/fonts/SCDream2.otf
        - asset: assets/fonts/SCDream3.otf
        - asset: assets/fonts/SCDream4.otf
        - asset: assets/fonts/SCDream5.otf
        - asset: assets/fonts/SCDream6.otf
        - asset: assets/fonts/SCDream7.otf
        - asset: assets/fonts/SCDream8.otf
        - asset: assets/fonts/SCDream9.otf



  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


